### ISSUE TITLE
Mouse acceleration too high while streaming

### ISSUE THREAD

**Issue by mrb113** [moonlight-stream/moonlight-common-c#18]
Mouse is too touchy while streaming - bug is probably in Common since it affects multiple clients.

**Comment by azsde** [comment]
I have the same issue

**Comment by sangdrax8** [comment]
I have the same issue, wasn't sure if there was something I had setup wrong or what.

**Comment by cgutman** [comment]
Looks like GFE 3.13 turns off mouse acceleration, so this will be fixed on NVIDIA's side.
