### ISSUE TITLE
Return specific error codes in PerformRTSPHandshake()

### ISSUE THREAD

**Issue by mrb113** [moonlight-stream/moonlight-common-c#2]
PerformRTSPHandshake in RTSPConnection.c only returns -1; not useful for debugging errors. 

@cgutman has a related issue here: https://github.com/moonlight-stream/moonlight-ios/issues/100 but opening an issue in this repo so I remember to do it :)

**Comment by cgutman** [comment]
Fixed by a5f59d206e6ad93ae3bbf2a5672ee319d19cb455
