### ISSUE TITLE
Questions about old GFE

### ISSUE THREAD

**Issue by d3m3vilurr** [moonlight-stream/moonlight-common-c#23]
i'm investigating xyzz/vita-moonlight#66 issue.
(reporter uploaded debug log http://pastebin.com/6Den03pv)

actually log shown EAGAIN, but reporter said can work on ipad.
so i made simple tcp socket testing tool, and tested moonlight tcp connection steps.
but my result, vita socket looks working well. :(

so, my questions are 1. is exists any next check list? 2. can make newer modified GFE?

**Comment by cgutman** [comment]
EAGAIN is returned if no data is received within the receive timeout or if the socket is non-blocking. Can you put some timestamps in the log? I would like to see whether it's failing in 10 seconds per the recv timeout. If it's failing earlier, it likely means there is some bug in the BSD sockets implementation.

**Comment by d3m3vilurr** [comment]
ok. i made new debug build. (but tester have vacation until next week)
and.. probably tcp socket open blocking mode in vita application.

**Comment by d3m3vilurr** [comment]
it's vita issue. :)
