### ISSUE TITLE
Feature request: Moonlight server

### ISSUE THREAD

**Issue by r57zone** [moonlight-stream/moonlight-common-c#29]
It would be nice to get Moonlight server. Can make a simple implementation (without GPU Nvidia feature) compatible with moonlight clients, and later someone can figure out (after reverse engineering) and make Nvidia feature (GPU support for streaming) and on AMD (feature off). However, in any case, we will have a good protocol for streaming games or apps without Nvidia GeForce Experience.

If simple implementation will load the CPU a little, then there is nothing to worry about. The main thing is that we can get a stable stream for mobile devices, TVs and other devices with Moonlight client.

Thanks.

UPD: Moonlight server - https://github.com/loki-47-6F-64/sunshine thanks Mirh for the info.
UPD2: Another moonlight server - https://open-stream.net/ & https://github.com/LS3solutions/openstream-server  thanks Mirh for the info.

**Comment by r57zone** [comment]
@cgutman maybe you are interested?

**Comment by Jorys-Paulin** [comment]
Having a dedicated moonlight server would be nice indeed, as it would allow us for more flexibility when it comes to adding features and more generally know how exactly the protocol and software works. Though it doesn't appear to be arriving anytime soon, I hope sometime it happens.

**Comment by Papermanzero** [comment]
A Moonlight Server would be also my question. Especially for ATI users and certain features (e.g. extended display and not only a clone display) it would be an advantage to have a Moonlight server.

**Comment by mirh** [comment]
So.. my [hopes](https://github.com/moonlight-stream/moonlight-common/issues/23#issuecomment-447585955) on the side of the switch community are dead in the water. 
On the other hand, it seems like microsoft is doing wonders [with miracast](https://www.theverge.com/2019/3/13/18263513/microsoft-xbox-one-pc-games-support-streaming-wireless-display-app-feature).

**Comment by LoneFenris** [comment]
Miracast has unfortunate limits (at present, anyway), like requiring a wireless negotiation to start the projection. This requires the projecting PC and Xbox to be in range of each others' adapters (and for the projecting PC to have a WiFi adpater). Once the negotiation is made, the actual stream can go over ethernet, but the negotiation has to be over WiFi.

**Comment by mirh** [comment]
If you read the app description it says it uses *Infracast*, which should be [microsoft speech](https://docs.microsoft.com/en-us/surface-hub/miracast-over-infrastructure) for *MS-MICE* (aka no P2P needed anymore, and supports ethernet)

Then, of course it's not like you could have used plain miracast, considering it doesn't carry controls.

**Comment by LoneFenris** [comment]
Yes, but unless you can show me differently, what I said still stands. MS-MICE allows for the actual streaming to be done over the infrastructure, but the initial device setup has to be done over WiDi.

According to https://docs.microsoft.com/en-us/surface-hub/miracast-over-infrastructure

>How it works
>Users attempt to connect to a Miracast receiver as they did previously. When the list of Miracast receivers is populated, Windows 10 will identify that the receiver is capable of supporting a connection over the infrastructure. When the user selects a Miracast receiver, Windows 10 will attempt to resolve the device's hostname via standard DNS, as well as via multicast DNS (mDNS). If the name is not resolvable via either DNS method, Windows 10 will fall back to establishing the Miracast session using the standard Wi-Fi direct connection.

This indicates to me that the initial device negotiation still has to happen over WiDi, and if during that negotiation, Windows determines that the receiver is capable of miracasting over the network, it will lookup the address of the receiver on the network and use that instead of WiDi going forward.

**Comment by mirh** [comment]
You can literally use it with ethernet on a normal desktop pc, I don't know what else there is much to say. 
"As they did previously" means it from a GUI point of view there. 
The initial device [negotiation](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-mice/940d808c-97f8-418e-a8a9-c471dc0d21bb) is just [the sink](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-mice/f6b2c820-ff11-4593-8b87-614868401a60) pinging the lan with a specific [bit set](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-mice/dc134434-62ec-431e-81ba-eda2ddce5227), and you are done.

**Comment by LoneFenris** [comment]
>You can literally use it with ethernet on a normal desktop pc

Except I literally haven't been able to unless I move the devices to the same room and enable the PC's WiFi adapter.

>The initial device negotiation is just the sink pinging the lan with a specific bit set, and you are done.

You keep seemingly unknowingly proving my point. From the [protocol details](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-mice/940d808c-97f8-418e-a8a9-c471dc0d21bb) link:

>Device discovery
>
>The Miracast over Infrastructure session starts with peer to peer (P2P) device discovery ([WF-P2P1.2] section 3.1.2), which a Miracast Source uses to find a device capable of performing the functions of a Miracast Sink. This includes the Source sending Probe Request frames ([WF-P2P1.2] section 4.2.2) and listening for Probe Response frames ([WF-P2P1.2] section 4.2.3) and Beacon frames ([WF-P2P1.2] section 4.2.1).
>
>Beacon frames are unsolicited broadcasts that advertise P2P devices. Probe Response frames are sent by a Sink in response to Probe Request frames sent by the Source. If the Source receives a Beacon or Probe Response that contains a WSC IE [WF-WSC2.0.2] Vendor Extension attribute (section 2.2.8), the Source checks the Capability attribute (section 2.2.8.1) for Miracast over Infrastructure support.
>
>If the Capability attribute specifies that Miracast over Infrastructure is not supported, the Source falls back to standard Miracast [WF-WSC2.0.2].
>
>If one or more IP Address attributes (section 2.2.8.5) are included, the Source can skip host name resolution.

**Comment by letalvoj** [comment]
According to https://github.com/moonlight-stream/moonlight-common-c/issues/41 there is no documentation to the protocol. Would anyone from the maintainers be willing to write a blogpost which describes the architecture a bit? Maybe it would help someone with starting with the server implementation.

**Comment by mirh** [comment]
So.. Just for the records, in-home-switching is back into seeing [some progress](https://github.com/jakibaki/In-Home-Switching/issues/51#issuecomment-613841639), maybe. 
And friendly reminder there's also a [bounty](https://github.com/vita-nuova/bounties/issues/4) open by the Vita guys.

**Comment by mirh** [comment]
Ladies and gents
https://github.com/loki-47-6F-64/sunshine

**Comment by Papermanzero** [comment]
Thanks!!!! Waiting for such a long time for that

**Comment by mirh** [comment]
Well, that seems to have died too. 
Now the only open "alive "solution seems to be this
https://open-stream.net/
https://github.com/LS3solutions/openstream-server

**Comment by mirh** [comment]
These could be at least featured/advertised somewhere official though.

**Comment by r57zone** [comment]
To get away from Nvidia need to make own server application, but since there are no others, the current options are the best solution.
