### ISSUE TITLE
questions about copyright

### ISSUE THREAD

**Issue by HongZhouyang** [moonlight-stream/moonlight-common-c#59]
Hi,author, I am interested in developing a new software to facilitate people's life basing on this powerful source code you big-god contributed. Is this a free source-code and anyone can use it to do anything? If not what should I do? 
Best wishes.

**Comment by cgutman** [comment]
Direct use of the code here is governed by the [GPLv3](https://github.com/moonlight-stream/moonlight-common-c/blob/master/LICENSE.txt) license.
